# docker-compose.yaml
version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.src
    ports:
      - "5000:5000"

  test:
    build:
      context: .
      dockerfile: Dockerfile.tests
    command: ["python", "-m", "unittest", "discover", "-s", "/tests"]
